### ISSUE TITLE
Can you share the depth estimation checkpoints

### ISSUE THREAD

**Issue by Zhefan-Xu** [mw9385/Collision-avoidance#6]
The original link of the FCRN checkpoint is not available. Can you share yours? Thank you in advance

**Comment by mw9385** [comment]
Hi, as the link is not available for now, I uploaded the model in the `save_model/est_model`. Please take a look at it. You could refer the issue #5 .

**Comment by Zhefan-Xu** [comment]
Thank you very much. I will have a try.
