### ISSUE TITLE
Depth estimator checkpoint

### ISSUE THREAD

**Issue by Jaumegopu** [mw9385/Collision-avoidance#7]
Heading into the depth estimaton model, the checkpoint file to set the parameters to the model is not available anymore. Did you face the same situation? How did you proceed to solve it? 
If you have such checkpoint file (named NYU_FCRN.ckpt in the project) could you provide it please?

**Comment by mw9385** [comment]
Hi, the weight files for the model parameters are not available anymore. However, I have a custom model that trained for outdoor environment. You need to change the code for model loading of the depth estimation. 

```
import tensorflow as tf
from tensorflow.keras.models import model_from_json

# Load the JSON file to reconstruct the model
json_file_path = 'est_model.json'
with open(json_file_path, 'r') as json_file:
    model_json = json_file.read()

# Reconstruct the model from the JSON data
model = model_from_json(model_json)

# Load the weights into the reconstructed model
weights_file_path = 'est_model.h5'
model.load_weights(weights_file_path)

print('Model loaded successfully.')
```

The models can be found in `saved_model/est_model.json` and `saved_model/est_model_v1.json`.

**Comment by Jaumegopu** [comment]
Thank you. I have checked the model and the batch input size expected is [none, 6, 128, 160, 1]. If I am not wrong 6 stand for the time steps and 1 for the channels (please correct me). Why is only one channel? Do I need to use a grey Image? Ando also, the image has a 3D shape but the model has a 5D expected input, do I need just to add two more dimensions or is there a specific requirement for those extra two dimensions? 
Thank you in advance

**Comment by mw9385** [comment]
Hi, as the model uses a depth image, so the channel should be 1.
